apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: bvrinfra-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/BODAPATI88/infra-homelab.git
    targetRevision: main
    path: apps/platform

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
