apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: bvrinfra-site

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bvrinfra-site

  template:
    metadata:
      labels:
        app: bvrinfra-site

    spec:
      nodeSelector:
        workload: apps
      imagePullSecrets:
      - name: ghcr-secret

      containers:
      - name: bvrinfra-site
        image: ghcr.io/bodapati88/bvrinfra-site:sha-678f758

        imagePullPolicy: Always

        ports:
        - containerPort: 80
