apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: bvrinfra-site

spec:
  ingressClassName: traefik

  rules:
  - host: bvrinfra.in

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: bvrinfra-site

            port:
              number: 80
