apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: infra-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/BODAPATI88/infra-homelab.git
    targetRevision: main
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: false

    syncOptions:
      - ServerSideApply=true
metadata:
  name: infra-app
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: bvrinfra-site=bodapati88/bvrinfra-site
    argocd-image-updater.argoproj.io/bvrinfra-site.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
