deploymentMode: SingleBinary

singleBinary:
  replicas: 1

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

chunksCache:
  enabled: false

monitoring:
  lokiCanary:
    enabled: false

  selfMonitoring:
    enabled: false

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  compactor:
    retention_enabled: true
    delete_request_store: filesystem

  limits_config:
    retention_period: 168h

  storage:
    type: filesystem

  useTestSchema: true
